//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECORESPRODUCT
    {
        public Nullable<long> PRODUCTMASTER { get; set; }
        public Nullable<int> RETAITOTALWEIGHT { get; set; }
        public Nullable<int> VARIANTCONFIGURATIONTECHNOLOGY { get; set; }
        public string RETAILCOLORGROUPID { get; set; }
        public string RETAILSIZEGROUPID { get; set; }
        public string RETAILSTYLEGROUPID { get; set; }
        public Nullable<int> ISPRODUCTVARIANTUNITCONVERSIONENABLED { get; set; }
        public long INSTANCERELATIONTYPE { get; set; }
        public string DISPLAYPRODUCTNUMBER { get; set; }
        public string SEARCHNAME { get; set; }
        public int PRODUCTTYPE { get; set; }
        public int PDSCWPRODUCT { get; set; }
        public string MODIFIEDBY { get; set; }
        public int RECVERSION { get; set; }
        public long RELATIONTYPE { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
