//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECORESPRODUCTTRANSLATION
    {
        public string DESCRIPTION { get; set; }
        public string NAME { get; set; }
        public long PRODUCT { get; set; }
        public string LANGUAGEID { get; set; }
        public string MODIFIEDBY { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
