//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTTABLE
    {
        public string ITEMID { get; set; }
        public int ITEMTYPE { get; set; }
        public int PURCHMODEL { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal WIDTH { get; set; }
        public int SALESMODEL { get; set; }
        public string COSTGROUPID { get; set; }
        public string REQGROUPID { get; set; }
        public decimal EPCMANAGER { get; set; }
        public string PRIMARYVENDORID { get; set; }
        public decimal NETWEIGHT { get; set; }
        public decimal DEPTH { get; set; }
        public decimal UNITVOLUME { get; set; }
        public string BOMUNITID { get; set; }
        public string ITEMPRICETOLERANCEGROUPID { get; set; }
        public decimal DENSITY { get; set; }
        public int COSTMODEL { get; set; }
        public int USEALTITEMID { get; set; }
        public string ALTITEMID { get; set; }
        public int MATCHINGPOLICY { get; set; }
        public string INTRACODE { get; set; }
        public int PRODFLUSHINGPRINCIP { get; set; }
        public decimal MINIMUMPALLETQUANTITY { get; set; }
        public int PBAITEMAUTOGENERATED { get; set; }
        public int WMSARRIVALHANDLINGTIME { get; set; }
        public int BOMMANUALRECEIPT { get; set; }
        public int PHANTOM { get; set; }
        public decimal INTRAUNIT { get; set; }
        public int BOMLEVEL { get; set; }
        public string BATCHNUMGROUPID { get; set; }
        public int AUTOREPORTFINISHED { get; set; }
        public string ORIGCOUNTRYREGIONID { get; set; }
        public decimal STATISTICSFACTOR { get; set; }
        public string ALTCONFIGID { get; set; }
        public string STANDARDCONFIGID { get; set; }
        public string PRODPOOLID { get; set; }
        public string PROPERTYID { get; set; }
        public int ABCTIEUP { get; set; }
        public int ABCREVENUE { get; set; }
        public int ABCVALUE { get; set; }
        public int ABCCONTRIBUTIONMARGIN { get; set; }
        public string COMMISSIONGROUPID { get; set; }
        public decimal SALESPERCENTMARKUP { get; set; }
        public decimal SALESCONTRIBUTIONRATIO { get; set; }
        public int SALESPRICEMODELBASIC { get; set; }
        public string NAMEALIAS { get; set; }
        public string PRODGROUPID { get; set; }
        public string PROJCATEGORYID { get; set; }
        public decimal GROSSDEPTH { get; set; }
        public decimal GROSSWIDTH { get; set; }
        public decimal GROSSHEIGHT { get; set; }
        public decimal STANDARDPALLETQUANTITY { get; set; }
        public decimal QTYPERLAYER { get; set; }
        public int SORTCODE { get; set; }
        public string SERIALNUMGROUPID { get; set; }
        public string ITEMBUYERGROUPID { get; set; }
        public decimal TAXPACKAGINGQTY { get; set; }
        public string WMSPALLETTYPEID { get; set; }
        public string ORIGSTATEID { get; set; }
        public int WMSPICKINGQTYTIME { get; set; }
        public decimal TARAWEIGHT { get; set; }
        public string PACKAGINGGROUPID { get; set; }
        public decimal SCRAPVAR { get; set; }
        public decimal SCRAPCONST { get; set; }
        public string STANDARDINVENTCOLORID { get; set; }
        public string STANDARDINVENTSIZEID { get; set; }
        public int ITEMDIMCOSTPRICE { get; set; }
        public string ALTINVENTSIZEID { get; set; }
        public string ALTINVENTCOLORID { get; set; }
        public int FORECASTDMPINCLUDE { get; set; }
        public long PRODUCT { get; set; }
        public int PALLETTAGGING { get; set; }
        public int ITEMTAGGINGLEVEL { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public int FISCALLIFOAVOIDCALC { get; set; }
        public decimal FISCALLIFONORMALVALUE { get; set; }
        public int FISCALLIFONORMALVALUECALC { get; set; }
        public string BOMCALCGROUPID { get; set; }
        public long INVENTFISCALLIFOGROUP { get; set; }
        public long NGPCODESTABLE_FR { get; set; }
        public string ORIGCOUNTYID { get; set; }
        public string TAXFISCALCLASSIFICATION_BR { get; set; }
        public int PBAITEMCONFIGURABLE { get; set; }
        public string PBAINVENTITEMGROUPID { get; set; }
        public int PBAHIDEDIALOG { get; set; }
        public int PBAHIDEAPPROVAL { get; set; }
        public int PBAAUTOSTART { get; set; }
        public int PBAMANDATORYCONFIG { get; set; }
        public string INVENTPRODUCTTYPE_BR { get; set; }
        public int TAXATIONORIGIN_BR { get; set; }
        public string TAXSERVICECODE_BR { get; set; }
        public long EXCISETARIFFCODES_IN { get; set; }
        public long CUSTOMSEXPORTTARIFFCODETABLE_IN { get; set; }
        public long CUSTOMSIMPORTTARIFFCODETABLE_IN { get; set; }
        public long SERVICECODETABLE_IN { get; set; }
        public long EXIMPRODUCTGROUPTABLE_IN { get; set; }
        public string PACKING_RU { get; set; }
        public string ASSETGROUPID_RU { get; set; }
        public string ASSETID_RU { get; set; }
        public int INTRASTATEXCLUDE { get; set; }
        public string INTRASTATPROCID_CZ { get; set; }
        public string PKWIUCODE_PL { get; set; }
        public string EXCEPTIONCODE_BR { get; set; }
        public int ICMSONSERVICE_BR { get; set; }
        public decimal PDSCWWMSSTANDARDPALLETQTY { get; set; }
        public decimal PDSCWWMSMINIMUMPALLETQTY { get; set; }
        public decimal PDSCWWMSQTYPERLAYER { get; set; }
        public string ALCOHOLMANUFACTURERID_RU { get; set; }
        public string ALCOHOLPRODUCTIONTYPEID_RU { get; set; }
        public decimal ALCOHOLSTRENGTH_RU { get; set; }
        public string ALTINVENTSTYLEID { get; set; }
        public decimal APPROXTAXVALUE_BR { get; set; }
        public int BATCHMERGEDATECALCULATIONMETHOD { get; set; }
        public System.Guid DAXINTEGRATIONKEY { get; set; }
        public string MARKUPCODE_RU { get; set; }
        public string NRTAXGROUP_LV { get; set; }
        public string PDSBASEATTRIBUTEID { get; set; }
        public int PDSBESTBEFORE { get; set; }
        public string PDSFREIGHTALLOCATIONGROUPID { get; set; }
        public string PDSITEMREBATEGROUPID { get; set; }
        public int PDSPOTENCYATTRIBRECORDING { get; set; }
        public int PDSSHELFADVICE { get; set; }
        public int PDSSHELFLIFE { get; set; }
        public decimal PDSTARGETFACTOR { get; set; }
        public int PDSVENDORCHECKITEM { get; set; }
        public string PMFPLANNINGITEMID { get; set; }
        public int PMFPRODUCTTYPE { get; set; }
        public decimal PMFYIELDPCT { get; set; }
        public string SADRATECODE_PL { get; set; }
        public int SKIPINTRACOMPANYSYNC_RU { get; set; }
        public string STANDARDINVENTSTYLEID { get; set; }
        public int DSA_IN { get; set; }
        public int EXCISERECORDTYPE_IN { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
