//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTTRAN
    {
        public string ITEMID { get; set; }
        public int STATUSISSUE { get; set; }
        public int INTERCOMPANYINVENTDIMTRANSFERRED { get; set; }
        public System.DateTime DATEPHYSICAL { get; set; }
        public decimal QTY { get; set; }
        public decimal COSTAMOUNTPOSTED { get; set; }
        public string CURRENCYCODE { get; set; }
        public string INVOICEID { get; set; }
        public string VOUCHER { get; set; }
        public System.DateTime DATEEXPECTED { get; set; }
        public System.DateTime DATEFINANCIAL { get; set; }
        public decimal COSTAMOUNTPHYSICAL { get; set; }
        public int STATUSRECEIPT { get; set; }
        public int PACKINGSLIPRETURNED { get; set; }
        public int INVOICERETURNED { get; set; }
        public string PACKINGSLIPID { get; set; }
        public string VOUCHERPHYSICAL { get; set; }
        public decimal COSTAMOUNTADJUSTMENT { get; set; }
        public System.DateTime SHIPPINGDATEREQUESTED { get; set; }
        public System.DateTime SHIPPINGDATECONFIRMED { get; set; }
        public decimal QTYSETTLED { get; set; }
        public decimal COSTAMOUNTSETTLED { get; set; }
        public int VALUEOPEN { get; set; }
        public string ACTIVITYNUMBER { get; set; }
        public System.DateTime DATESTATUS { get; set; }
        public decimal COSTAMOUNTSTD { get; set; }
        public System.DateTime DATECLOSED { get; set; }
        public string PICKINGROUTEID { get; set; }
        public decimal COSTAMOUNTOPERATIONS { get; set; }
        public long RETURNINVENTTRANSORIGIN { get; set; }
        public string PROJID { get; set; }
        public string PROJCATEGORYID { get; set; }
        public string INVENTDIMID { get; set; }
        public long MARKINGREFINVENTTRANSORIGIN { get; set; }
        public int INVENTDIMFIXED { get; set; }
        public System.DateTime DATEINVENT { get; set; }
        public string TRANSCHILDREFID { get; set; }
        public int TRANSCHILDTYPE { get; set; }
        public int TIMEEXPECTED { get; set; }
        public decimal REVENUEAMOUNTPHYSICAL { get; set; }
        public string PROJADJUSTREFID { get; set; }
        public decimal TAXAMOUNTPHYSICAL { get; set; }
        public long INVENTTRANSORIGIN { get; set; }
        public int STORNO_RU { get; set; }
        public int STORNOPHYSICAL_RU { get; set; }
        public string INVENTDIMIDSALES_RU { get; set; }
        public int GROUPREFTYPE_RU { get; set; }
        public string GROUPREFID_RU { get; set; }
        public decimal COSTAMOUNTSECCURPOSTED_RU { get; set; }
        public decimal COSTAMOUNTSECCURPHYSICAL_RU { get; set; }
        public decimal COSTAMOUNTSECCURADJUSTMENT_RU { get; set; }
        public System.DateTime DATECLOSEDSECCUR_RU { get; set; }
        public decimal QTYSETTLEDSECCUR_RU { get; set; }
        public decimal COSTAMOUNTSETTLEDSECCUR_RU { get; set; }
        public int VALUEOPENSECCUR_RU { get; set; }
        public decimal COSTAMOUNTSTDSECCUR_RU { get; set; }
        public long INVENTTRANSORIGINDELIVERY_RU { get; set; }
        public long INVENTTRANSORIGINSALES_RU { get; set; }
        public long INVENTTRANSORIGINTRANSIT_RU { get; set; }
        public decimal PDSCWQTY { get; set; }
        public decimal PDSCWSETTLED { get; set; }
        public long NONFINANCIALTRANSFERINVENTCLOSING { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
