//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTSUM
    {
        public string ITEMID { get; set; }
        public decimal POSTEDQTY { get; set; }
        public decimal POSTEDVALUE { get; set; }
        public decimal DEDUCTED { get; set; }
        public decimal RECEIVED { get; set; }
        public decimal RESERVPHYSICAL { get; set; }
        public decimal RESERVORDERED { get; set; }
        public decimal ONORDER { get; set; }
        public decimal ORDERED { get; set; }
        public decimal QUOTATIONISSUE { get; set; }
        public decimal QUOTATIONRECEIPT { get; set; }
        public string INVENTDIMID { get; set; }
        public int CLOSED { get; set; }
        public decimal REGISTERED { get; set; }
        public decimal PICKED { get; set; }
        public decimal AVAILORDERED { get; set; }
        public decimal AVAILPHYSICAL { get; set; }
        public decimal PHYSICALVALUE { get; set; }
        public decimal ARRIVED { get; set; }
        public decimal PHYSICALINVENT { get; set; }
        public int CLOSEDQTY { get; set; }
        public System.DateTime LASTUPDDATEPHYSICAL { get; set; }
        public System.DateTime LASTUPDDATEEXPECTED { get; set; }
        public decimal POSTEDVALUESECCUR_RU { get; set; }
        public decimal PHYSICALVALUESECCUR_RU { get; set; }
        public decimal PDSCWARRIVED { get; set; }
        public decimal PDSCWAVAILORDERED { get; set; }
        public decimal PDSCWAVAILPHYSICAL { get; set; }
        public decimal PDSCWDEDUCTED { get; set; }
        public decimal PDSCWONORDER { get; set; }
        public decimal PDSCWORDERED { get; set; }
        public decimal PDSCWPHYSICALINVENT { get; set; }
        public decimal PDSCWPICKED { get; set; }
        public decimal PDSCWPOSTEDQTY { get; set; }
        public decimal PDSCWQUOTATIONISSUE { get; set; }
        public decimal PDSCWQUOTATIONRECEIPT { get; set; }
        public decimal PDSCWRECEIVED { get; set; }
        public decimal PDSCWREGISTERED { get; set; }
        public decimal PDSCWRESERVORDERED { get; set; }
        public decimal PDSCWRESERVPHYSICAL { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
