//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTLOCATION
    {
        public string INVENTLOCATIONID { get; set; }
        public string NAME { get; set; }
        public int MANUAL { get; set; }
        public string EMPTYPALLETLOCATION { get; set; }
        public decimal MAXPICKINGROUTEVOLUME { get; set; }
        public int PICKINGLINETIME { get; set; }
        public int MAXPICKINGROUTETIME { get; set; }
        public string WMSLOCATIONIDDEFAULTRECEIPT { get; set; }
        public string WMSLOCATIONIDDEFAULTISSUE { get; set; }
        public string INVENTLOCATIONIDREQMAIN { get; set; }
        public int REQREFILL { get; set; }
        public int INVENTLOCATIONTYPE { get; set; }
        public string INVENTLOCATIONIDQUARANTINE { get; set; }
        public int INVENTLOCATIONLEVEL { get; set; }
        public string REQCALENDARID { get; set; }
        public int WMSAISLENAMEACTIVE { get; set; }
        public int WMSRACKNAMEACTIVE { get; set; }
        public string WMSRACKFORMAT { get; set; }
        public int WMSLEVELNAMEACTIVE { get; set; }
        public string WMSLEVELFORMAT { get; set; }
        public int WMSPOSITIONNAMEACTIVE { get; set; }
        public string WMSPOSITIONFORMAT { get; set; }
        public int USEWMSORDERS { get; set; }
        public string INVENTLOCATIONIDTRANSIT { get; set; }
        public string VENDACCOUNT { get; set; }
        public string BRANCHNUMBER { get; set; }
        public string INVENTSITEID { get; set; }
        public int INVENTCOUNTINGGROUP_BR { get; set; }
        public string CUSTACCOUNT_BR { get; set; }
        public int INVENTPROFILETYPE_RU { get; set; }
        public string INVENTPROFILEID_RU { get; set; }
        public string INVENTLOCATIONIDGOODSINROUTE_RU { get; set; }
        public string WMSLOCATIONIDGOODSINROUTE_RU { get; set; }
        public string ACTIVITYTYPE_RU { get; set; }
        public string NUMBERSEQUENCEGROUP_RU { get; set; }
        public decimal RETAILWEIGHTEX1 { get; set; }
        public int FSHSTORE { get; set; }
        public string RBODEFAULTWMSPALLETID { get; set; }
        public string RBODEFAULTWMSLOCATIONID { get; set; }
        public string RBODEFAULTINVENTPROFILEID_RU { get; set; }
        public int ALLOWLABORSTANDARDS { get; set; }
        public int ALLOWMARKINGRESERVATIONREMOVAL { get; set; }
        public int CONSOLIDATESHIPATRTW { get; set; }
        public string CUSTACCOUNT_HU { get; set; }
        public int CYCLECOUNTALLOWPALLETMOVE { get; set; }
        public int DECREMENTLOADLINE { get; set; }
        public string DEFAULTKANBANFINISHEDGOODSLOCATION { get; set; }
        public string DEFAULTPRODUCTIONFINISHGOODSLOCATION { get; set; }
        public string DEFAULTSHIPMAINTENANCELOC { get; set; }
        public string DEFAULTSTATUSID { get; set; }
        public int PRINTBOLBEFORESHIPCONFIRM { get; set; }
        public int PRODRESERVEONLYWHSE { get; set; }
        public int REMOVEINVENTBLOCKINGONSTATUSCHANGE { get; set; }
        public int RESERVEATLOADPOST { get; set; }
        public int RETAILINVENTNEGFINANCIAL { get; set; }
        public int RETAILINVENTNEGPHYSICAL { get; set; }
        public string RETAILWMSLOCATIONIDDEFAULTRETURN { get; set; }
        public string RETAILWMSPALLETIDDEFAULTRETURN { get; set; }
        public int UNIQUECHECKDIGITS { get; set; }
        public string VENDACCOUNTCUSTOM_RU { get; set; }
        public int WAREHOUSEAUTORELEASERESERVATION { get; set; }
        public int WHSENABLED { get; set; }
        public string DEFAULTCONTAINERTYPECODE { get; set; }
        public string DEFAULTPRODUCTIONINPUTLOCATION { get; set; }
        public string DEFAULTRETURNCREDITONLYLOCATION { get; set; }
        public int WHSRAWMATERIALPOLICY { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
