//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTSITE
    {
        public string SITEID { get; set; }
        public string NAME { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public int TIMEZONE { get; set; }
        public string ORDERENTRYDEADLINEGROUPID { get; set; }
        public string DEFAULTINVENTSTATUSID { get; set; }
        public long TAXBRANCHREFRECID { get; set; }
        public int ISRECEIVINGWAREHOUSEOVERRIDEALLOWED { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
