//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMachineLearning
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicrosoftDynamicsAXEntities : DbContext
    {
        public MicrosoftDynamicsAXEntities()
            : base("name=MicrosoftDynamicsAXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INVENTDIM> INVENTDIMs { get; set; }
        public virtual DbSet<INVENTLOCATION> INVENTLOCATIONs { get; set; }
        public virtual DbSet<INVENTSITE> INVENTSITEs { get; set; }
        public virtual DbSet<INVENTSUM> INVENTSUMs { get; set; }
        public virtual DbSet<INVENTTABLE> INVENTTABLEs { get; set; }
        public virtual DbSet<INVENTTRAN> INVENTTRANS { get; set; }
        public virtual DbSet<ECORESPRODUCT> ECORESPRODUCTs { get; set; }
        public virtual DbSet<ECORESPRODUCTTRANSLATION> ECORESPRODUCTTRANSLATIONs { get; set; }
    }
}
